"""auto update

Revision ID: 2536f4906042
Revises: b437f2316054
Create Date: 2026-05-19 10:20:12.335057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2536f4906042'
down_revision: Union[str, Sequence[str], None] = 'b437f2316054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('printer_type', sa.String(), nullable=False),
    sa.Column('printer_name', sa.String(), nullable=False),
    sa.Column('printnode_api_key', sa.String(), nullable=True),
    sa.Column('printnode_printer_id', sa.String(), nullable=True),
    sa.Column('paper_width', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_settings_id'), 'printer_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printer_settings_id'), table_name='printer_settings')
    op.drop_table('printer_settings')
    # ### end Alembic commands ###