"""auto update

Revision ID: 44c0170ee295
Revises: e72533028f92
Create Date: 2026-05-27 08:53:07.971533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c0170ee295'
down_revision: Union[str, Sequence[str], None] = 'e72533028f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'calendar_event_id')
    op.drop_column('reservations', 'client_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('client_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('calendar_event_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###