"""auto update

Revision ID: f12d0a9b500d
Revises: 44c0170ee295
Create Date: 2026-05-27 11:14:28.575574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12d0a9b500d'
down_revision: Union[str, Sequence[str], None] = '44c0170ee295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('client_email', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('calendar_event_id', sa.String(), nullable=True))
    op.alter_column('reservations', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reservations', 'calendar_event_id')
    op.drop_column('reservations', 'client_email')
    # ### end Alembic commands ###